map_file: "/home/rdaneel/mapf_benchmark/mapf-map/warehouse-10-20-10-2-1.map"
scen_file: "/home/rdaneel/mapf_benchmark/scen-random/warehouse-10-20-10-2-1-random-1.scen"
num_of_agents: 100
pixel_per_move: 2
moves: 2
plot_ag_num: true
delay: 0.05